name: Test & Deploy

on: [push, pull_request]
jobs:
  test-and-deploy:
    name: Test & Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Set up node and npm
      uses: actions/setup-node@v1
      with:
        version: 12.9.1

    - name: Install node dependencies
      run: npm install

    - name: Set up ruby and bundler
      uses: actions/setup-ruby@v1
      with:
        version: 2.6

    - name: Install ruby dependencies
      run: |
        gem install bundler
        bundle install

    - name: Set up python and pip
      uses: actions/setup-python@v1
      with:
        version: 3.7
        architecture: x64

    - name: Install AWS CLI
      run: pip install --user awscli

    - name: Build the blog
      run: npm run build-prod

    - name: Run tests
      run: ./scripts/travis.sh

    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      if: success() && github.event_name == 'push' && github.ref == 'refs/heads/source'
      run: |
        echo "event name ${{ github.event_name }}"
        echo "ref ${{ github.ref }}"
        echo "head_ref ${{ github.head_ref }}"
        echo "base_ref ${{ github.base_ref }}"
        echo "woooooooooo!"
