name: Test

on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Set up node and npm
      uses: actions/setup-node@v1
      with:
        version: 12.9.1

    - name: Install node dependencies
      run: npm install

    - name: Set up ruby and bundler
      uses: actions/setup-ruby@v1
      with:
        version: 2.6

    - name: Install ruby dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build the blog
      run: npm run build-prod

    - name: Run tests
      run: ./scripts/travis.sh
